org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

loom_version=1.15.5

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2

mod_version=0.1
maven_group=thunder.hack
archives_base_name=Niggahack

# Dependencies
fabric_version=0.141.3+1.21.11
orbit_version=0.2.3
netty_version=4.1.90.Final
